package engine

import (
	"path/filepath"
	"testing"

	"github.com/sketchain/nfuse/internal/model"
	"github.com/sketchain/nfuse/internal/store"
)

// newTokenEngine builds a Controller over a fresh temp store and a cold-start
// fakeMgr (table absent, never sampled), so token behavior can be exercised
// without a kernel.
func newTokenEngine(t *testing.T) *Controller {
	t.Helper()
	st, err := store.Open(filepath.Join(t.TempDir(), "t.db"))
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	t.Cleanup(func() { st.Close() })
	ctrl, err := New(st, &fakeMgr{exists: false}, Options{Logf: t.Logf})
	if err != nil {
		t.Fatalf("engine: %v", err)
	}
	return ctrl
}

// tokenOf returns the current token the engine holds for the given account id.
func tokenOf(t *testing.T, c *Controller, id int64) string {
	t.Helper()
	for _, av := range func() []AccountView { v, _ := c.View(); return v }() {
		if av.Account.ID == id {
			return av.Account.Token
		}
	}
	t.Fatalf("account %d not found in view", id)
	return ""
}

// TestAddAccountGeneratesUniqueToken: a new account is born with a 16-letter
// token, and two accounts get distinct tokens (both distinct from the master).
func TestAddAccountGeneratesUniqueToken(t *testing.T) {
	c := newTokenEngine(t)
	id1, err := c.AddAccount("a", model.TierUnlimited, 0, 1)
	if err != nil {
		t.Fatalf("add a: %v", err)
	}
	id2, err := c.AddAccount("b", model.TierUnlimited, 0, 1)
	if err != nil {
		t.Fatalf("add b: %v", err)
	}
	t1, t2 := tokenOf(t, c, id1), tokenOf(t, c, id2)
	if len(t1) != model.TokenLength || len(t2) != model.TokenLength {
		t.Fatalf("token lengths = %d,%d, want %d", len(t1), len(t2), model.TokenLength)
	}
	if t1 == t2 {
		t.Fatalf("two accounts share a token %q", t1)
	}
	if m := c.MasterToken(); m == t1 || m == t2 {
		t.Fatalf("account token collides with master token %q", m)
	}
}

// TestQueryByToken: an account token returns just that account; the master token
// returns all; an unknown/empty token returns not-ok.
func TestQueryByToken(t *testing.T) {
	c := newTokenEngine(t)
	id1, _ := c.AddAccount("alice", model.TierMonthly, 10, 1)
	id2, _ := c.AddAccount("bob", model.TierUnlimited, 0, 1)
	t1 := tokenOf(t, c, id1)

	views, all, ok := c.QueryByToken(t1)
	if !ok || all {
		t.Fatalf("account token query: ok=%v all=%v, want ok, not-all", ok, all)
	}
	if len(views) != 1 || views[0].Account.ID != id1 {
		t.Fatalf("account token returned %+v, want just alice", views)
	}

	views, all, ok = c.QueryByToken(c.MasterToken())
	if !ok || !all {
		t.Fatalf("master token query: ok=%v all=%v, want ok and all", ok, all)
	}
	if len(views) != 2 {
		t.Fatalf("master token returned %d accounts, want 2", len(views))
	}

	if _, _, ok := c.QueryByToken("nope"); ok {
		t.Fatalf("unknown token must not resolve")
	}
	if _, _, ok := c.QueryByToken(""); ok {
		t.Fatalf("empty token must not resolve")
	}
	_ = id2
}

// TestRegenerateToken: regeneration issues a new token, the old one stops
// resolving, and the new one resolves to the same account.
func TestRegenerateToken(t *testing.T) {
	c := newTokenEngine(t)
	id, _ := c.AddAccount("alice", model.TierUnlimited, 0, 1)
	old := tokenOf(t, c, id)

	fresh, err := c.RegenerateToken(id)
	if err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	if fresh == old {
		t.Fatalf("regenerated token equals old %q", old)
	}
	if tokenOf(t, c, id) != fresh {
		t.Fatalf("view token = %q, want the regenerated %q", tokenOf(t, c, id), fresh)
	}
	if _, _, ok := c.QueryByToken(old); ok {
		t.Fatalf("old token must stop resolving after regeneration")
	}
	if _, _, ok := c.QueryByToken(fresh); !ok {
		t.Fatalf("new token must resolve")
	}

	if _, err := c.RegenerateToken(9999); err == nil {
		t.Fatalf("regenerating a missing account must error")
	}
}

// TestRegenerateMasterToken: regeneration replaces the master token; the old one
// stops resolving as master, the new one returns all accounts.
func TestRegenerateMasterToken(t *testing.T) {
	c := newTokenEngine(t)
	c.AddAccount("alice", model.TierUnlimited, 0, 1)
	old := c.MasterToken()

	fresh, err := c.RegenerateMasterToken()
	if err != nil {
		t.Fatalf("regenerate master: %v", err)
	}
	if fresh == old || c.MasterToken() != fresh {
		t.Fatalf("master token not replaced: old=%q fresh=%q now=%q", old, fresh, c.MasterToken())
	}
	if _, _, ok := c.QueryByToken(old); ok {
		t.Fatalf("old master token must stop resolving")
	}
	if _, all, ok := c.QueryByToken(fresh); !ok || !all {
		t.Fatalf("new master token must resolve to all accounts")
	}
}

// TestTokensSurviveReload: tokens generated by the engine are persisted, so a
// second engine over the same DB sees the same tokens (no re-backfill).
func TestTokensSurviveReload(t *testing.T) {
	st, err := store.Open(filepath.Join(t.TempDir(), "t.db"))
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer st.Close()

	c1, err := New(st, &fakeMgr{exists: false}, Options{Logf: t.Logf})
	if err != nil {
		t.Fatalf("engine 1: %v", err)
	}
	id, _ := c1.AddAccount("alice", model.TierUnlimited, 0, 1)
	want := tokenOf(t, c1, id)
	wantMaster := c1.MasterToken()

	c2, err := New(st, &fakeMgr{exists: false}, Options{Logf: t.Logf})
	if err != nil {
		t.Fatalf("engine 2: %v", err)
	}
	if got := tokenOf(t, c2, id); got != want {
		t.Fatalf("token after reload = %q, want %q", got, want)
	}
	if got := c2.MasterToken(); got != wantMaster {
		t.Fatalf("master token after reload = %q, want %q", got, wantMaster)
	}
}
